language: python

# 2.6 is not available for networkx requirement
python:
  - 2.7
  - 3.4
  - 3.5

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install libhdf5-serial-dev

# Install packages
install:
  - pip install --upgrade pip
  - pip install wheel
  - pip install numpy
  - pip install scipy
  - pip install pandas
  - pip install coveralls
  - python setup.py install

script:
  - source activate $TRAVIS_PYTHON_VERSION
  - nosetests --with-doctest --with-coverage --cover-tests --cover-package=tsgettoolbox --cover-branches --cover-erase

after_success:
  - coveralls
